  select 	
	 TRIM(DPID.SRCH_CHAR_VAL)	 AS  SRC_DPID,
	 CI_SA.SA_ID	 AS  SRC_SA_ID,
	 TRIM(CI_SA.SA_TYPE_CD)	 AS  SA_TYPE_CD,
	 TRIM(SA_TYPE.DESCR)	 AS  SA_TYPE_DESCR,
	 TRIM(CI_SA.SA_STATUS_FLG)	 AS  SA_STATUS_FLAG,
	 TRIM(SA_STATUS.DESCR)	 AS  SA_STATUS_DESCR,
	 CI_SA.START_DT	 AS  SA_START_DATE,
	 CI_SA.END_DT	 AS  SA_END_DATE,
	 TRIM(EXTRACTVALUE(XMLTYPE(NVL(CI_SA.SA_DATA_AREA, '<notes/>')), '/notes/samplePoint'))	 AS  TRADER_NAME,
	 TRIM(EXTRACTVALUE(XMLTYPE(NVL(CI_SA.SA_DATA_AREA, '<notes/>')), '/notes/stwReference'))	 AS  STW_REFERENCE,
     TRIM(REV_DT.ADHOC_CHAR_VAL) AS  CONSENT_REVIEW_COMPLETED_DATE, --- completed review date
     TO_DATE(SUBSTR(TRIM(EXTRACTVALUE(XMLTYPE(NVL(CI_SA.SA_DATA_AREA, '<notes/>')), '/notes/reviewDate')), 1, 10), 'YYYY-MM-DD')	 AS  CONSENT_NEXT_REVIEW_DUE_DATE, --- consent next review date
	 CI_SA.JRN_EFF_START_DTTM	 AS  EFF_START_DTTM,
	 CI_SA.JRN_SLICING_TS	 AS  JRN_DATE,
	 B1_PROD_INST.DSI	 AS  DATA_SOURCE_IND,
	 'I'	 AS  IND_UPDATE
from	(((LIMS1REP.CI_SA_CHAR DPID  INNER JOIN  MDADM.B1_PROD_INSTANCE B1_PROD_INST  
    ON  B1_PROD_INST.PROD_FLG = 'CCB'
AND DPID.CHAR_TYPE_CD = 'DPID'
AND DPID.JRN_FLAG <> 'D'
 )  INNER JOIN  LIMS1REP.CI_SA CI_SA  
    ON  CI_SA.SA_ID = DPID.SA_ID
AND CI_SA.JRN_FLAG <> 'D'
---- Completed Review Date Join ----
LEFT OUTER JOIN  LIMS1REP.CI_SA_CHAR REV_DT  
    ON  CI_SA.SA_ID = REV_DT.SA_ID
AND REV_DT.CHAR_TYPE_CD = 'CM-TECRD'
AND DECODE(CI_SA.JRN_EFF_START_DTTM,TO_DATE('01-JAN-1950','DD-MON-RRRR'),CI_SA.START_DT,CI_SA.JRN_EFF_START_DTTM) >= REV_DT.EFFDT
AND DECODE(CI_SA.JRN_EFF_START_DTTM,TO_DATE('01-JAN-1950','DD-MON-RRRR'),CI_SA.START_DT,CI_SA.JRN_EFF_START_DTTM) < REV_DT.JRN_EFF_END_DTTM
AND REV_DT.JRN_FLAG <> 'D'
---- Completed Review Date Join ----
 )  INNER JOIN  LIMS1REP.CI_SA_TYPE_L SA_TYPE  
    ON  SA_TYPE.CIS_DIVISION=CI_SA.CIS_DIVISION
 AND SA_TYPE.SA_TYPE_CD = CI_SA.SA_TYPE_CD 
 AND SA_TYPE.LANGUAGE_CD = B1_PROD_INST.LANGUAGE_CD
 AND SA_TYPE.JRN_CURRENT_FLAG = 1
 )  INNER JOIN  LIMS1REP.CI_LOOKUP_VAL_L SA_STATUS  
    ON  CI_SA.SA_STATUS_FLG = SA_STATUS.FIELD_VALUE
AND SA_STATUS.FIELD_NAME = 'SA_STATUS_FLG'
AND SA_STATUS.LANGUAGE_CD = B1_PROD_INST.LANGUAGE_CD
AND SA_STATUS.JRN_CURRENT_FLAG = 1
where	(1=1);